// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvv5BAzmLopnHbLYrb0HLuGo3_wR_vNU',
    appId: '1:471616480362:web:486197275a7d13571f1613',
    messagingSenderId: '471616480362',
    projectId: 'activity-17-47973',
    authDomain: 'activity-17-47973.firebaseapp.com',
    storageBucket: 'activity-17-47973.firebasestorage.app',
    measurementId: 'G-7D5KG21TE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmvNdCHTdHsciMeBd_dEebnT8lrw7su3U',
    appId: '1:471616480362:android:42840496ed4bb53e1f1613',
    messagingSenderId: '471616480362',
    projectId: 'activity-17-47973',
    storageBucket: 'activity-17-47973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZznGg5hDmYbXNYciJ5ZqLpJqEgGJlMCo',
    appId: '1:471616480362:ios:0486c51a9f0636331f1613',
    messagingSenderId: '471616480362',
    projectId: 'activity-17-47973',
    storageBucket: 'activity-17-47973.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZznGg5hDmYbXNYciJ5ZqLpJqEgGJlMCo',
    appId: '1:471616480362:ios:0486c51a9f0636331f1613',
    messagingSenderId: '471616480362',
    projectId: 'activity-17-47973',
    storageBucket: 'activity-17-47973.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpvv5BAzmLopnHbLYrb0HLuGo3_wR_vNU',
    appId: '1:471616480362:web:115f1f9a732115231f1613',
    messagingSenderId: '471616480362',
    projectId: 'activity-17-47973',
    authDomain: 'activity-17-47973.firebaseapp.com',
    storageBucket: 'activity-17-47973.firebasestorage.app',
    measurementId: 'G-1QFLTSHLJQ',
  );
}
